sudo: false
language: python

env:
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17
  - TOX_ENV=py33-django18
  - TOX_ENV=py33-django19
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
