sudo: false
language: python

python:
  - 3.5

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django110

before_install:
  - pip install codecov

install:
  - pip install tox

after_success:
  - codecov

script:
  - tox -e $TOX_ENV
