sudo: false
language: python
cache: pip

matrix:
  include:
    - env: TOX_ENV=flake8
    - python: 2.7
      env: TOX_ENV=py27-django18
    - python: 3.3
      env: TOX_ENV=py33-django18
    - python: 3.4
      env: TOX_ENV=py34-django18
    - python: 3.5
      env: TOX_ENV=py35-django18
    - python: 2.7
      env: TOX_ENV=py27-django110
    - python: 3.4
      env: TOX_ENV=py34-django110
    - python: 3.5
      env: TOX_ENV=py35-django110
    - python: 2.7
      env: TOX_ENV=py27-django111
    - python: 3.4
      env: TOX_ENV=py34-django111
    - python: 3.5
      env: TOX_ENV=py35-django111
    - python: 3.6
      env: TOX_ENV=py36-django111

before_install:
  - pip install codecov

install:
  - pip install tox

after_success:
  - codecov

script:
  - tox -e $TOX_ENV
